/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/button/CardButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/button/HalfButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/common/EmptyStateScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/common/LoadingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/DottedLine`; params?: Router.UnknownInputParams; } | { pathname: `/components/wrapper/LayoutWrapper`; params?: Router.UnknownInputParams; } | { pathname: `/theme/color`; params?: Router.UnknownInputParams; } | { pathname: `/theme/dimensions`; params?: Router.UnknownInputParams; } | { pathname: `/theme/font`; params?: Router.UnknownInputParams; } | { pathname: `/utils/hasHan`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/quiz/[level]` | `/quiz/[level]`, params: Router.UnknownInputParams & { level: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/components/button/CardButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/button/HalfButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/common/EmptyStateScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/components/common/LoadingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ui/DottedLine`; params?: Router.UnknownOutputParams; } | { pathname: `/components/wrapper/LayoutWrapper`; params?: Router.UnknownOutputParams; } | { pathname: `/theme/color`; params?: Router.UnknownOutputParams; } | { pathname: `/theme/dimensions`; params?: Router.UnknownOutputParams; } | { pathname: `/theme/font`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/hasHan`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(pages)'}/quiz/[level]` | `/quiz/[level]`, params: Router.UnknownOutputParams & { level: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/components/button/CardButton${`?${string}` | `#${string}` | ''}` | `/components/button/HalfButton${`?${string}` | `#${string}` | ''}` | `/components/common/EmptyStateScreen${`?${string}` | `#${string}` | ''}` | `/components/common/LoadingScreen${`?${string}` | `#${string}` | ''}` | `/components/ui/DottedLine${`?${string}` | `#${string}` | ''}` | `/components/wrapper/LayoutWrapper${`?${string}` | `#${string}` | ''}` | `/theme/color${`?${string}` | `#${string}` | ''}` | `/theme/dimensions${`?${string}` | `#${string}` | ''}` | `/theme/font${`?${string}` | `#${string}` | ''}` | `/utils/hasHan${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/components/button/CardButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/button/HalfButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/common/EmptyStateScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/common/LoadingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/ui/DottedLine`; params?: Router.UnknownInputParams; } | { pathname: `/components/wrapper/LayoutWrapper`; params?: Router.UnknownInputParams; } | { pathname: `/theme/color`; params?: Router.UnknownInputParams; } | { pathname: `/theme/dimensions`; params?: Router.UnknownInputParams; } | { pathname: `/theme/font`; params?: Router.UnknownInputParams; } | { pathname: `/utils/hasHan`; params?: Router.UnknownInputParams; } | `${'/(pages)'}/quiz/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/quiz/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(pages)'}/quiz/[level]` | `/quiz/[level]`, params: Router.UnknownInputParams & { level: string | number; } };
    }
  }
}
